# -*- coding: utf-8 -*-
#BASIC PATH TO YOLO-DIR
MODEL_PATH = "yolo-coco"


#THE MINIMUM CONFIDENCE OF OBJ
MIN_CONFID = 0.3


#MINIMUM THRESHOLD FOR NONMAXIMA SUPPRESSION
NMS_THRESHLD = 0.5


#WHETHER TO USE GPU OR NOT
USE_GPU = False


#MINIMUM SOCIAL-DISTANCE
MIN_DISTANCE = 50

